### ISSUE TITLE
Help with server connection

### ISSUE THREAD

**Issue by Torwz** [0blu/SimpleQueue#3]
Ive added this plugin to my server, players join the queue but do not join the server even when there is space available, only admins can connect to the server. Any help would be appreciated!

**Comment by 0blu** [comment]
Hey, this plugin is pretty old, did you check the [permissions](https://github.com/0blu/SimpleQueue#permissions) already?

**Comment by Torwz** [comment]
Ive looked through all the permissions, there isnt a permission to allow everyone to join? Is there something Im missing. I figured add the plugin and it should just work?

**Comment by 0blu** [comment]
So you want some players to join without being queued?
Did you try `simplequeue.ignoreslotlimit`?

If the slot limit is not reached everyone can join

**Comment by Torwz** [comment]
Okay update after some testing, we figured out the queue plugin takes up 1 slot of the server! Its working functionally now in 1.16.4 which im sure you will be pleased to know. Thank you for the replies, do you know if there would ever be a possibility of making so players sit in the queue and it auto connects when there is a space instead of keep having to try and connect from the server menu? Thanks so much for the help anyway!

**Comment by 0blu** [comment]
Great to hear, I never thought that a 4 year old plugin still works.
Unfortunately I don't think that it is possible to do this.

As far as I know, there are some plugins that will send the player to another server/queue world,
but this is not possible which this plugin and would also require Bungeecord.
